name: inventory_optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - numpy=1.23.5
  - pandas=1.5.2
  - scipy=1.9.3
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - pip:
      - pulp==2.7.0
      - deap==1.3.3
      - folium==0.14.0
      - tqdm==4.64.1
